development:
  adapter: mysql2
  database: atlasmonkey_dev
  pool: 5
  timeout: 5000
  username: root
  password:
  host: localhost

production:
  adapter: mysql2
  database: atlasmonkey_production
  pool: 5
  timeout: 5000
  username: root
  password: atlasmonkey$4311!@
  host: localhost
